collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4761905
color:
  saturation: 0.5125313
  brandStrength: 0.4924812
  lightness: 0.2061404
  brandColors:
    - '#000000'
    - '#0188EC'
    - '#FEFBF4'
    - '#FFF200'
    - '#8D5001'
  rhythmicContrast: 0
layout_spectrum: 0.03132832
name: dayDreamhk
