collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.5106516
  brandColors:
    - '#FFFFFF'
    - '#E62F17'
    - '#989799'
    - '#403B36'
    - '#64FCFE'
  rhythmicContrast: 0
typography_spectrum: 0.4761905
layout_spectrum: 0.03132832
name: dayDreamhk
