collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4129073
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#E50013'
    - '#000000'
    - '#2AB4A7'
    - '#F29719'
  rhythmicContrast: 0.8195488
typography_spectrum: 0.4761905
layout_spectrum: 0.5426065
name: dayDreamhk
